//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xTrader.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XTRADER_DIALOG              102
#define IDD_LOGIN                       104
#define IDD_DLG_NOTICE                  105
#define IDS_TRADE_STAT                  106
#define IDS_MD_STAT                     107
#define IDS_RESPINFO                    108
#define IDS_SFETIME                     109
#define IDS_DCETIME                     110
#define IDS_ZCETIME                     111
#define IDS_CFXTIME                     112
#define IDS_DISCONTIPS                  113
#define IDR_CONFBAK                     114
#define IDR_MAINFRAME                   128
#define IDR_MAIMENU                     129
#define IDM_POPMENU                     130
#define IDS_TITLE                       131
#define IDD_DLG_NETSET                  132
#define IDS_STREMPTY                    133
#define IDD_DLG_MODPASS                 134
#define IDS_CFMPASSERR                  135
#define IDS_STRTIPS                     136
#define IDD_BFTRANS                     137
#define IDS_USERPASSERR                 138
#define IDS_ACCPASSERR                  139
#define IDR_LSTRMENU1                   140
#define IDS_MODPASSOK                   141
#define IDD_DLG_GENMRFEE                142
#define IDD_DLG_HISETM                  143
#define IDS_MD_TIPS                     144
#define IDS_TRADE_TIPS                  145
#define IDS_SFE_TIPS                    146
#define IDS_DCE_TIPS                    147
#define IDS_ZCE_TIPS                    148
#define IDS_CFX_TIPS                    149
#define IDS_BFTRANS_OK                  150
#define IDS_SOCKADDR                    151
#define IDD_DLG_BFDETAILS               152
#define IDS_QRYBKERR                    153
#define IDD_DLG_RECENT                  154
#define IDC_COMB_SER                    1001
#define IDC_NETSET                      1002
#define IDC_ISPLIST                     1003
#define IDC_USERNAME                    1004
#define IDC_PASSWORD                    1005
#define IDC_SAVE                        1006
#define IDC_PROGRESS                    1007
#define IDC_LOGINFO                     1008
#define IDC_MDPAN                       1009
#define IDC_S1P                         1010
#define IDC_S1V                         1011
#define IDC_LASTP                       1012
#define IDC_LASTV                       1013
#define IDC_B1P                         1014
#define IDC_B1V                         1015
#define IDC_STOTAL                      1016
#define IDC_VTOTAL                      1017
#define IDC_SOPEN                       1018
#define IDC_VOPEN                       1019
#define IDC_SUPDOWN                     1020
#define IDC_DUPDOWN                     1021
#define IDC_SHIGHEST                    1022
#define IDC_DHIGHEST                    1023
#define IDC_SOPT                        1024
#define IDC_DOPT                        1025
#define IDC_SLOWEST                     1026
#define IDC_DLOWEST                     1027
#define IDC_SSMP                        1028
#define IDC_DSMP                        1029
#define IDC_UPTIME                      1030
#define IDC_SS1                         1031
#define IDC_SLAST                       1032
#define IDC_SB1                         1033
#define IDC_INST                        1034
#define ID_EXIT                         1035
#define ID_USERINFO                     1036
#define ID_TRANSBF                      1037
#define ID_HELP_ABOUT                   1038
#define ID_TIPS                         1039
#define ID_TOOL_TRANS                   1040
#define ID_VIEW_TOP                     1041
#define IDC_COMB_BS                     1042
#define IDC_COMB_OC                     1043
#define IDC_BTORDER                     1044
#define IDC_EDVOL                       1045
#define IDC_EDPRICE                     1046
#define IDC_SPINVOL                     1047
#define IDC_SPINPRICE                   1048
#define IDC_CHK_NEWP                    1049
#define IDC_LST_ODINF                   1050
#define IDC_LST_ONROAD                  1051
#define IDC_LST_TRADE                   1052
#define IDC_LST_INVPOS                  1053
#define IDC_LST_ALLINST                 1054
#define IDC_TABPAGE                     1055
#define IDC_GRPACC                      1056
#define IDC_CPYK                        1057
#define IDC_HPYK                        1058
#define IDC_TDFEE                       1059
#define IDC_BTQRYACC                    1060
#define IDSHELL_RESTORE                 1061
#define IDSHELL_SYNC                    1062
#define IDSHELL_ABOUT                   1063
#define IDSHELL_EXIT                    1064
#define IDC_NTMSG                       1065
#define IDR_TIPS                        1066
#define IDC_COMBO_NETTYPE               1067
#define IDC_CHK_SOCK                    1068
#define IDC_SOCKSERV                    1069
#define IDC_SOCK_PORT                   1070
#define IDC_SK_USER                     1071
#define IDC_SKPWD                       1072
#define IDC_LST_MD                      1074
#define ID_MODPASS                      1075
#define IDC_ORIPASS                     1076
#define IDC_NEWPASS                     1077
#define IDC_NEWPASSCFM                  1078
#define IDC_TRADEPASS                   1079
#define IDC_ACCPASS                     1080
#define IDC_CBBKLST                     1081
#define IDC_ACCPASSWD                   1082
#define IDC_BKPASSWD                    1083
#define IDC_TRANSAMT                    1084
#define IDC_CBEXHTYPE                   1086
#define IDC_BTNQRYBK                    1087
#define IDC_BTNQRYFT                    1088
#define IDC_BTNFT2BK                    1089
#define IDC_BTNBK2FT                    1090
#define IDC_QRYDETAIL                   1091
#define IDC_BT_GENMR                    1092
#define IDC_BT_GENFEE                   1093
#define IDC_GENSTAT                     1094
#define IDC_DTPICK                      1095
#define IDC_BT_QRYDAY                   1096
#define IDC_BT_QRYMONTH                 1097
#define IDC_BT_SAVEFILE                 1098
#define IDC_EDIT_HISOD                  1099
#define IDC_LST_BFDETAILS               1100
#define IDC_BTCLOSE                     1101
#define IDC_STAVOL                      1102
#define IDC_BKR_LIST                    1103
#define IDC_LBRECENT                    1104
#define IDC_CHK_RECENT                  1105
#define IDC_EXTRA                       1107
#define ID_CANCEL_ORD                   2000
#define ID_CANCEL_ALL                   2001
#define ID_MOD_DSJ                      2002
#define ID_CFMMC                        2003
#define ID_GENMDFEE                     2004
#define ID_HISETTINF                    2005
#define ID_HKEY                         2006
#define ID_CSV_EXPORT                   2007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         2008
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
